version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: test

  test:
    desc: Test and lint.
    cmds:
      - go mod verify
      - go test ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.40.1 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache
      - go mod tidy -v
